[package]
name = "anchor_tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "anchortutorial" 
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.18.2"
